import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { cp, readFile, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import sharp from 'sharp';
import { z } from 'zod';

const tsxCli = createRequire(import.meta.url).resolve('tsx/cli');

for (const scenario of [
  { name: 'repo-only without OneDrive', source: false, missing: true, damage: '', code: 0, integrity: 'REPOSITORY_VERIFIED' },
  { name: 'explicit intact source', source: true, missing: false, damage: '', code: 0, integrity: 'REPOSITORY_AND_EXTERNAL_VERIFIED' },
  { name: 'explicit missing source', source: true, missing: true, damage: '', code: 2, integrity: 'INPUT_OUTPUT_ERROR' },
  ...['inicio_membego/screen.png', 'inicio_membego/code.html', 'retail_commercial_mobile/DESIGN.md'].flatMap((damage) => [
    { name: `repo drift ${damage}`, source: false, missing: true, damage, code: 2, integrity: 'REFERENCE_DRIFT' },
    { name: `explicit source drift ${damage}`, source: true, missing: false, damage, code: 2, integrity: 'REFERENCE_DRIFT' },
  ]),
]) {
  test(`Node portability when ${scenario.name}`, { concurrency: true }, async (t) => {
    // Given: a checkout fixture with unchanged pinned assets/hashes and an unavailable provenance location.
    await mkdir('.omo/start-work/r0-visual', { recursive: true });
    const dir = resolve(await mkdtemp('.omo/start-work/r0-visual/test-portability-'));
    t.after(() => rm(dir, { recursive: true, force: true }));
    const docs = join(dir, 'docs/transformacion-membego');
    await mkdir(docs, { recursive: true });
    await cp('docs/transformacion-membego/stitch', join(docs, 'stitch'), { recursive: true });
    const manifest = z.object({ source_root: z.string() }).passthrough()
      .parse(JSON.parse(await readFile('docs/transformacion-membego/stitch-manifest.json', 'utf8')));
    await writeFile(join(docs, 'stitch-manifest.json'), JSON.stringify({ ...manifest, source_root: join(dir, 'OneDrive-absent') }));
    const source = join(dir, 'source');
    if (!scenario.missing) await cp(join(docs, 'stitch'), source, { recursive: true });
    if (scenario.damage) await writeFile(join(scenario.source ? source : join(docs, 'stitch'), scenario.damage), 'drift');
    const actual = resolve('docs/transformacion-membego/stitch/inicio_membego/screen.png');
    const metadata = await sharp(await readFile(actual)).metadata();
    await writeFile(join(dir, 'metadata.json'), JSON.stringify({ label: 'APPLICATION_CAPTURE',
      sha256: createHash('sha256').update(await readFile(actual)).digest('hex'), browser: 'contract-fixture', version: 'test',
      viewport: { width: metadata.width, height: metadata.height }, dpr: 1, locale: 'en-US', timezone: 'UTC',
      fontsReady: true, animationPolicy: 'disabled', scale: 'css', fullPage: false, capturedAt: '2026-01-01T00:00:00.000Z' }));
    await mkdir(join(dir, '.omo/start-work/r0-visual'), { recursive: true });
    const env: NodeJS.ProcessEnv = { ...process.env, PATH: '' };
    for (const key of Object.keys(env)) if (key.toLowerCase() === 'path') env[key] = '';
    // When: the installed Node/tsx CLI runs with no executable discoverable on PATH.
    const result = spawnSync(process.execPath, [tsxCli, resolve('scripts/visual/compare.ts'), '--screen', 'inicio_membego',
      '--actual', actual, '--metadata', 'metadata.json', '--out', '.omo/start-work/r0-visual/result',
      ...(scenario.source ? ['--source-root', source] : [])], { cwd: dir, env, encoding: 'utf8', timeout: 30_000 });
    // Then: portability never bypasses pinned hashes; this contract fixture never grants app fidelity.
    assert.equal(result.status, scenario.code, result.stdout + result.stderr);
    const report = z.object({ reason: z.string(), referenceIntegrity: z.string().optional(), fidelityApproval: z.literal('NOT_GRANTED') })
      .parse(JSON.parse(result.stdout));
    assert.equal(report.referenceIntegrity ?? report.reason, scenario.integrity);
  });
}

test('reference metadata matches when reading the twelve recorded PNGs', async () => {
  // Given: the existing manifest, never regenerated by this test.
  const manifest = z.object({
    capture_metadata: z.object({ css_viewport: z.null(), device_pixel_ratio: z.null(), export_scale: z.null() }),
    screens: z.array(z.object({ id: z.string(), png: z.object({
      path: z.string(), sha256: z.string(), width: z.number(), height: z.number(),
    }) })).length(12),
  }).parse(JSON.parse(await readFile('docs/transformacion-membego/stitch-manifest.json', 'utf8')));
  // When: decode and hash the actual versioned bytes.
  const observations = await Promise.all(manifest.screens.map(async ({ id, png }) => {
    const bytes = await readFile(png.path);
    const metadata = await sharp(bytes).metadata();
    return { id, hash: createHash('sha256').update(bytes).digest('hex'),
      width: metadata.width, height: metadata.height, expected: png };
  }));
  // Then: metadata describes bytes, not an invented CSS viewport.
  assert.equal(new Set(observations.map(({ id }) => id)).size, 12);
  for (const observation of observations) {
    assert.equal(observation.hash, observation.expected.sha256);
    assert.equal(observation.width, observation.expected.width);
    assert.equal(observation.height, observation.expected.height);
  }
});

test('CLI is executable when help is requested', () => {
  // Given: the public comparator entrypoint.
  const entry = 'scripts/visual/compare.ts';
  // When: invoke it through the installed runtime.
  const result = spawnSync(process.execPath, [tsxCli, entry, '--help'], { encoding: 'utf8' });
  // Then: absence of the comparator fails this contract before implementation.
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /--screen/);
});

const scenarios = [
  { name: 'identical', actual: 'same.png', options: [], code: 0, reason: 'PIXELS_EQUAL', changed: 0 },
  { name: 'changed', actual: 'changed.png', options: [], code: 1, reason: 'PIXEL_MISMATCH', changed: 1 },
  { name: 'size', actual: 'size.png', options: [], code: 1, reason: 'DIMENSION_MISMATCH', changed: null },
  { name: 'corrupt', actual: 'corrupt.png', options: [], code: 2, reason: 'INVALID_IMAGE' },
  { name: 'explicit tolerance', actual: 'changed.png', options: ['--max-ratio', '0.01'], code: 0, reason: 'WITHIN_EXPLICIT_TOLERANCE', changed: 1 },
  { name: 'excess tolerance', actual: 'same.png', options: ['--max-ratio', '1'], code: 2, reason: 'INVALID_ARGUMENT' },
  { name: 'negative tolerance', actual: 'same.png', options: ['--max-ratio', '-1'], code: 2, reason: 'INVALID_ARGUMENT' },
  { name: 'nonfinite tolerance', actual: 'same.png', options: ['--max-ratio', 'NaN'], code: 2, reason: 'INVALID_ARGUMENT' },
] as const;

for (const scenario of scenarios) {
  test(`comparison enforces its contract when ${scenario.name}`, async (t) => {
    // Given: isolated real PNG files; only one of 100 pixels is altered.
    await mkdir('.omo/start-work/r0-visual', { recursive: true });
    const dir = await mkdtemp('.omo/start-work/r0-visual/test-');
    t.after(() => rm(dir, { recursive: true, force: true }));
    const raw = Buffer.alloc(400, 255);
    await sharp(raw, { raw: { width: 10, height: 10, channels: 4 } }).png().toFile(join(dir, 'same.png'));
    raw[0] = 0;
    await sharp(raw, { raw: { width: 10, height: 10, channels: 4 } }).png().toFile(join(dir, 'changed.png'));
    await sharp({ create: { width: 11, height: 10, channels: 4, background: '#fff' } }).png().toFile(join(dir, 'size.png'));
    await writeFile(join(dir, 'corrupt.png'), 'not an image');
    // When: run the actual public CLI, not a mocked adapter.
    const result = spawnSync(process.execPath, [tsxCli, 'scripts/visual/compare.ts',
      '--self-test-reference', join(dir, 'same.png'), '--actual', join(dir, scenario.actual),
      '--out', join(dir, 'result'), ...scenario.options], { encoding: 'utf8' });
    // Then: exit status and machine-readable result distinguish the failure.
    assert.equal(result.status, scenario.code, result.stderr);
    const report = z.object({ reason: z.string(), changedPixels: z.number().nullable().optional(),
      totalPixels: z.number().optional(), ratio: z.number().nullable().optional(), referenceHash: z.string().optional(), actualHash: z.string().optional(),
      tolerance: z.number().optional(), label: z.string().optional(), diffArtifact: z.string().nullable().optional(),
    }).parse(JSON.parse(result.stdout));
    assert.equal(report.reason, scenario.reason);
    if ('changed' in scenario) {
      assert.equal(report.changedPixels, scenario.changed);
      assert.equal(report.label, 'TOOLING_SELF_TEST');
      assert.equal(report.tolerance, scenario.options.length ? 0.01 : 0);
      assert.equal(report.totalPixels, 100);
      assert.equal(report.ratio, scenario.changed === null ? null : scenario.changed / 100);
      assert.equal(report.referenceHash, createHash('sha256').update(await readFile(join(dir, 'same.png'))).digest('hex'));
      assert.equal(report.actualHash, createHash('sha256').update(await readFile(join(dir, scenario.actual))).digest('hex'));
      if (report.diffArtifact) assert.equal((await sharp(await readFile(report.diffArtifact)).metadata()).width, 10);
    }
  });
}

for (const args of [[], ['--screen', 'unknown'], ['--wat'], ['--max-ratio', ''], ['--help', '--wat']]) {
  test(`CLI rejects invalid arguments when given ${JSON.stringify(args)}`, () => {
    // Given: invalid public arguments. When: execute the real entrypoint.
    const result = spawnSync(process.execPath, [tsxCli, 'scripts/visual/compare.ts', ...args], { encoding: 'utf8' });
    // Then: it cannot silently pass or accept an unknown option.
    assert.equal(result.status, 2);
    assert.doesNotThrow(() => JSON.parse(result.stdout));
  });
}

test('reference integrity fails when bytes drift from the recorded hash', async () => {
  // Given: a recorded digest independent of the changed bytes.
  const { verifyDigest } = await import('../scripts/visual/reference.js');
  const expected = createHash('sha256').update('original').digest('hex');
  // When / Then: the shared source boundary rejects drift.
  assert.throws(() => verifyDigest(Buffer.from('changed'), expected), { code: 'REFERENCE_DRIFT' });
});

test('output cannot overwrite inputs when an existing PNG is selected', async () => {
  // Given: an existing, manifest-owned reference.
  const path = 'docs/transformacion-membego/stitch/inicio_membego/screen.png';
  const before = await readFile(path);
  // When: try to use it as the output destination.
  const result = spawnSync(process.execPath, [tsxCli, 'scripts/visual/compare.ts', '--self-test-reference', path,
    '--actual', path, '--out', path], { encoding: 'utf8' });
  // Then: rejection leaves the original bytes intact.
  assert.equal(result.status, 2);
  assert.deepEqual(await readFile(path), before);
});

test('all known IDs resolve when repository references are intact', async () => {
  // Given: the authoritative twelve-screen contract.
  const { loadReference } = await import('../scripts/visual/reference.js');
  const manifest = z.object({ screens: z.array(z.object({ id: z.string() })) })
    .parse(JSON.parse(await readFile('docs/transformacion-membego/stitch-manifest.json', 'utf8')));
  // When: resolve each ID through the application comparison boundary.
  const references = await Promise.all(manifest.screens.map(({ id }) => loadReference(id)));
  // Then: all twelve resolve and their eighteen route mappings survive.
  assert.equal(references.length, 12);
  assert.equal(references.flatMap(({ screen }) => screen.routes).length, 18);
});

test('unknown screen is rejected when lookup uses a complete request', async () => {
  // Given: an ID absent from the contract.
  const { loadReference } = await import('../scripts/visual/reference.js');
  // When / Then: lookup cannot fall back to the first screen.
  await assert.rejects(loadReference('unknown'), { code: 'UNKNOWN_SCREEN' });
});

test('alpha-only delta fails when RGB channels remain identical', async () => {
  // Given: one pixel whose alpha changes, with identical RGB.
  const { comparePixels } = await import('../scripts/visual/pixels.js');
  const reference = await sharp(Buffer.from([255, 0, 0, 255]), { raw: { width: 1, height: 1, channels: 4 } }).png().toBuffer();
  const actual = await sharp(Buffer.from([255, 0, 0, 254]), { raw: { width: 1, height: 1, channels: 4 } }).png().toBuffer();
  // When: compare without tolerance.
  const report = await comparePixels(reference, actual);
  // Then: alpha cannot silently disappear from the comparison.
  assert.equal(report.pass, false);
  assert.equal(report.changedPixels, 1);
  assert.equal(report.ratio, 1);
});

test('corrupt reference fails when actual input is valid', async () => {
  // Given: a damaged PNG reference and a valid actual PNG.
  const { comparePixels } = await import('../scripts/visual/pixels.js');
  const actual = await sharp({ create: { width: 1, height: 1, channels: 4, background: '#fff' } }).png().toBuffer();
  // When / Then: decode failure is explicit, not a pixel pass.
  await assert.rejects(comparePixels(actual.subarray(0, 30), actual), { code: 'INVALID_IMAGE' });
});

test('CLI blocks drift before reading application capture when a repository reference is damaged', async (t) => {
  // Given: a disposable working directory with the unchanged manifest and damaged reference bytes.
  await mkdir('.omo/start-work/r0-visual', { recursive: true });
  const dir = await mkdtemp('.omo/start-work/r0-visual/test-drift-');
  t.after(() => rm(dir, { recursive: true, force: true }));
  const docs = join(dir, 'docs/transformacion-membego');
  await mkdir(join(docs, 'stitch/inicio_membego'), { recursive: true });
  await writeFile(join(docs, 'stitch-manifest.json'), await readFile('docs/transformacion-membego/stitch-manifest.json'));
  await writeFile(join(docs, 'stitch/inicio_membego/screen.png'), 'deliberate drift');
  // When: application mode runs without any actual capture available.
  const result = spawnSync(process.execPath, [tsxCli, resolve('scripts/visual/compare.ts'), '--screen', 'inicio_membego',
    '--actual', 'absent.png', '--metadata', 'absent.json', '--out', 'unused'], { cwd: dir, encoding: 'utf8' });
  // Then: reference drift, not missing capture, is the first blocking failure.
  assert.equal(result.status, 2);
  assert.equal(z.object({ reason: z.string() }).parse(JSON.parse(result.stdout)).reason, 'REFERENCE_DRIFT');
});

test('CLI rejects missing metadata when targeting a real screen', () => {
  // Given: known screen plus actual reference bytes, but no authenticated capture metadata.
  const path = 'docs/transformacion-membego/stitch/inicio_membego/screen.png';
  // When: application mode is invoked without metadata.
  const result = spawnSync(process.execPath, [tsxCli, 'scripts/visual/compare.ts', '--screen', 'inicio_membego',
    '--actual', path, '--out', '.omo/start-work/r0-visual/unused'], { encoding: 'utf8' });
  // Then: bitmap identity alone cannot qualify as an application capture.
  assert.equal(result.status, 2);
  assert.equal(z.object({ reason: z.string() }).parse(JSON.parse(result.stdout)).reason, 'INVALID_METADATA');
});

test('output directory rejects reuse when evidence already exists', async (t) => {
  // Given: an existing evidence directory containing an input image.
  const { createEvidenceDirectory } = await import('../scripts/visual/evidence.js');
  await mkdir('.omo/start-work/r0-visual', { recursive: true });
  const dir = await mkdtemp('.omo/start-work/r0-visual/test-output-');
  t.after(() => rm(dir, { recursive: true, force: true }));
  await writeFile(join(dir, 'input.png'), 'protected');
  // When / Then: exclusive directory creation rejects reuse, never replacing its files.
  await assert.rejects(createEvidenceDirectory(dir), { code: 'EEXIST' });
});
