-- MEMBEGO SUPPLY 2.0 · SLICE 8 · FIDELIZACIÓN
-- Parte 1/2: SOLO los tipos enumerados.
--
-- Van en su propia migración porque PostgreSQL no permite usar un valor nuevo
-- de un enum en la misma transacción que lo crea. Separarlos deja la parte 2
-- libre de ese límite. Es la misma convención de los Slices 5, 6 y 7.

DO $$ BEGIN CREATE TYPE "SupplyV2LoyaltyOwner" AS ENUM ('MEMBEGO', 'SUPPLIER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2LoyaltyProgramStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2LoyaltyModality" AS ENUM ('MEMBERSHIPS', 'REFERRALS', 'POINTS', 'REWARDS'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2PointsAccrualBasis" AS ENUM ('CONTRACTUAL_VALUE', 'CUSTOMER_PAID'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2MembershipPlanKind" AS ENUM ('FREE', 'PAID', 'GRANTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2MembershipPlanStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'PAUSED', 'ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CustomerMembershipStatus" AS ENUM ('PENDING_PAYMENT', 'SCHEDULED', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2MembershipBenefitKind" AS ENUM ('BENEFIT', 'COUPON', 'POINTS_MULTIPLIER', 'EARLY_ACCESS'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2ReferralStatus" AS ENUM ('LINK_OPENED', 'SIGNED_UP', 'VERIFIED', 'PURCHASE_ELIGIBLE', 'REWARD_PENDING', 'REWARD_APPROVED', 'REWARD_GRANTED', 'REWARD_VOIDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2ReferralRewardKind" AS ENUM ('BONUS', 'COUPON', 'POINTS', 'SUPPLIER_BENEFIT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2PointsMovementType" AS ENUM ('EARNED', 'PENDING', 'AVAILABLE', 'RESERVED', 'REDEEMED', 'RELEASED', 'EXPIRED', 'REVERSED', 'ADMIN_ADJUSTMENT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2PointsSource" AS ENUM ('PURCHASE', 'REFERRAL', 'MEMBERSHIP', 'REWARD', 'PROMOTION', 'ADMIN'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2RewardKind" AS ENUM ('COUPON', 'BENEFIT', 'FREE_PRODUCT', 'SERVICE', 'PARTIAL_BONUS'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2RewardStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'EXHAUSTED', 'EXPIRED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2RewardClaimStatus" AS ENUM ('RESERVED', 'CLAIMED', 'DELIVERED', 'EXPIRED', 'CANCELLED', 'REVERSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2LoyaltyEventType" AS ENUM ('PROGRAM_CREATED', 'PROGRAM_SUBMITTED', 'PROGRAM_APPROVED', 'PROGRAM_REJECTED', 'PROGRAM_PAUSED', 'PROGRAM_RESUMED', 'PROGRAM_COMPLETED', 'PROGRAM_CANCELLED', 'PLAN_CREATED', 'PLAN_UPDATED', 'PLAN_PUBLISHED', 'PLAN_PAUSED', 'PLAN_ARCHIVED', 'MEMBERSHIP_STARTED', 'MEMBERSHIP_ACTIVATED', 'MEMBERSHIP_RENEWED', 'MEMBERSHIP_EXPIRED', 'MEMBERSHIP_CANCELLED', 'MEMBERSHIP_SUSPENDED', 'MEMBERSHIP_GRANTED', 'REFERRAL_CODE_CREATED', 'REFERRAL_SIGNED_UP', 'REFERRAL_VERIFIED', 'REFERRAL_ELIGIBLE', 'REFERRAL_REWARD_APPROVED', 'REFERRAL_REWARD_GRANTED', 'REFERRAL_REWARD_VOIDED', 'POINTS_EARNED', 'POINTS_AVAILABLE', 'POINTS_EXPIRED', 'POINTS_ADJUSTED', 'REWARD_CREATED', 'REWARD_PUBLISHED', 'REWARD_CLAIMED', 'REWARD_DELIVERED', 'REWARD_REVERSED', 'BUDGET_WAIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2OrderKind" AS ENUM ('OFFER', 'MEMBERSHIP'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Bitácora: las 36 acciones del Slice 8. Un ajuste manual de puntos deja
-- rastro aquí; ninguna ruta borra movimientos para tapar un error (§43).
DO $$ BEGIN
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_CREATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_SUBMITTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_APPROVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_REJECTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_PAUSED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_RESUMED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_CANCELLED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_PROGRAM_COMPLETED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_LOYALTY_BUDGET_WAIVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_PLAN_CREATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_PLAN_UPDATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_PLAN_PUBLISHED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_PLAN_PAUSED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_PLAN_ARCHIVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_STARTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_ACTIVATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_RENEWED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_GRANTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_CANCELLED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_SUSPENDED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_MEMBERSHIP_EXPIRED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_CODE_CREATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_SIGNED_UP';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_ELIGIBLE';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_REWARD_APPROVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_REWARD_GRANTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REFERRAL_REWARD_VOIDED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_POINTS_EARNED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_POINTS_AVAILABLE';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_POINTS_EXPIRED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_POINTS_ADJUSTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REWARD_CREATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REWARD_APPROVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REWARD_CLAIMED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REWARD_DELIVERED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_REWARD_REVERSED';
EXCEPTION WHEN undefined_object THEN NULL;
END $$;
