-- MEMBEGO SUPPLY 2.0 · SLICE 6 · BENEFICIOS ECONÓMICOS (bonos, descuentos, financiación combinada)
-- Parte 1/2: SOLO tipos y valores de enum. PostgreSQL no permite usar un valor
-- recién añadido a un enum dentro de la misma transacción que lo crea, así que
-- la estructura va en la migración siguiente. Idempotente: se puede repetir.

DO $$ BEGIN
    CREATE TYPE "SupplyV2CommissionBase" AS ENUM ('CONTRACTUAL_SALE_VALUE', 'CUSTOMER_PAID_AMOUNT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitFunding" AS ENUM ('MEMBEGO', 'SUPPLIER', 'SHARED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitValueType" AS ENUM ('FIXED_AMOUNT', 'PERCENTAGE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitScope" AS ENUM ('SPECIFIC_OFFER', 'CATALOG_ITEM', 'SUPPLIER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'EXHAUSTED', 'EXPIRED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2CustomerBenefitStatus" AS ENUM ('AVAILABLE', 'EXHAUSTED', 'EXPIRED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitReservationStatus" AS ENUM ('ACTIVE', 'APPLIED', 'RELEASED', 'EXPIRED', 'REVERSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "SupplyV2BenefitMovementType" AS ENUM ('GRANTED', 'RESERVED', 'APPLIED', 'RELEASED', 'EXPIRED', 'REVERSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_CREATED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_APPROVED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_PAUSED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_RESUMED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_CANCELLED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_GRANTED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_GRANT_CANCELLED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_RESERVED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_APPLIED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_RELEASED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_BENEFIT_REVERSED';

ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_ORDER_COVERED_BY_BENEFIT';

ALTER TYPE "SupplyV2EconomicEventType" ADD VALUE IF NOT EXISTS 'MEMBEGO_SUBSIDY';

ALTER TYPE "SupplyV2PaymentStatus" ADD VALUE IF NOT EXISTS 'COVERED_BY_BENEFIT';
