-- MEMBEGO SUPPLY 2.0 · SLICE 7 · CAMPAÑAS, PROMOCIONES Y CUPONES
-- Parte 1/2: SOLO los tipos enumerados.
--
-- Van en su propia migración porque PostgreSQL no permite usar un valor nuevo
-- de un enum en la misma transacción que lo crea. Separarlos deja la parte 2
-- libre de ese límite.

DO $$ BEGIN CREATE TYPE "SupplyV2CampaignOrganizer" AS ENUM ('MEMBEGO', 'SUPPLIER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CampaignStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CampaignAudience" AS ENUM ('ALL', 'NEW_CUSTOMERS', 'RETURNING_CUSTOMERS', 'PAST_CAMPAIGN', 'SELECTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CouponKind" AS ENUM ('PUBLIC', 'PRIVATE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CouponStatus" AS ENUM ('ACTIVE', 'EXHAUSTED', 'EXPIRED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CouponRedemptionStatus" AS ENUM ('RESERVED', 'APPLIED', 'RELEASED', 'REVERSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "SupplyV2CampaignEventType" AS ENUM ('CREATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PUBLISHED', 'PAUSED', 'RESUMED', 'COMPLETED', 'CANCELLED', 'OFFER_ADDED', 'OFFER_REMOVED', 'BENEFIT_ATTACHED', 'COUPONS_GENERATED', 'AUDIENCE_ASSIGNED', 'BUDGET_WAIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Bitácora: las acciones del Slice 7.
DO $$ BEGIN
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_CREATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_SUBMITTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_APPROVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_REJECTED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_PUBLISHED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_PAUSED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_RESUMED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_CANCELLED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_COMPLETED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_CAMPAIGN_BUDGET_WAIVED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_COUPONS_GENERATED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_COUPON_CANCELLED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_COUPON_APPLIED';
    ALTER TYPE "AuditAccion" ADD VALUE IF NOT EXISTS 'SUPPLY_V2_COUPON_RELEASED';
EXCEPTION WHEN undefined_object THEN NULL;
END $$;
